<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Miko-Lap-148" failures="11" tests="11" name="authentication.VerifyOTP" time="10.633" errors="0" timestamp="2022-10-09T19:56:46 IST" skipped="0">
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_016_VerifyOTPTests" time="0.856">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_016_VerifyOTPTests(VerifyOTP.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_016_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_021_VerifyOTPTests" time="0.872">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_021_VerifyOTPTests(VerifyOTP.java:167)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_021_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_020_VerifyOTPTests" time="0.836">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_020_VerifyOTPTests(VerifyOTP.java:144)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_020_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_022_VerifyOTPTests" time="0.850">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Verifying the Status code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Verifying the Status code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_022_VerifyOTPTests(VerifyOTP.java:189)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_022_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_027_VerifyOTPTests" time="0.862">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Verifying the Status code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Verifying the Status code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_027_VerifyOTPTests(VerifyOTP.java:293)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_027_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_026_VerifyOTPTests" time="0.843">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Verifying the Status code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Verifying the Status code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_026_VerifyOTPTests(VerifyOTP.java:272)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_026_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_018_VerifyOTPTests" time="0.906">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_018_VerifyOTPTests(VerifyOTP.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_018_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_019_VerifyOTPTests" time="1.150">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_019_VerifyOTPTests(VerifyOTP.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_019_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_024_VerifyOTPTests" time="0.848">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Verifying the Status code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Verifying the Status code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_024_VerifyOTPTests(VerifyOTP.java:230)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_024_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_025_VerifyOTPTests" time="0.906">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null],
	Response showing different status code. expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Response showing different status Code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null],
	Verifying the Status code expected [400] but found [422],
	Response showing different status message expected [true] but found [false],
	Response showing different message expected [Incorrect or expired OTP code] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null],
Response showing different status code. expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Response showing different status Code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null],
Verifying the Status code expected [400] but found [422],
Response showing different status message expected [true] but found [false],
Response showing different message expected [Incorrect or expired OTP code] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_025_VerifyOTPTests(VerifyOTP.java:251)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_025_VerifyOTPTests -->
  <system-out/>
  <testcase classname="authentication.VerifyOTP" name="mIKO_AUTH_017_VerifyOTPTests" time="1.704">
    <failure message="The following asserts failed:
	Response showing different Status Code expected [200] but found [422],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [+919555555555] but found [null],
	Response showing different Status Code expected [200] but found [400],
	Response showing different Status message expected [true] but found [false],
	Response showing different mobile no expected [user05@testing.com] but found [null]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Response showing different Status Code expected [200] but found [422],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [+919555555555] but found [null],
Response showing different Status Code expected [200] but found [400],
Response showing different Status message expected [true] but found [false],
Response showing different mobile no expected [user05@testing.com] but found [null]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at authentication.VerifyOTP.mIKO_AUTH_017_VerifyOTPTests(VerifyOTP.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- mIKO_AUTH_017_VerifyOTPTests -->
  <system-out/>
</testsuite> <!-- authentication.VerifyOTP -->
